### ISSUE TITLE
Create Random Shark Sighting Generator

### ISSUE THREAD

**Issue by tohearen** [sriksrik7/Jaws#4]
We must write a python script that randomly outputs shark data in the defined data format.

**Comment by sriksrik7** [comment]
Random Shark Sighting Generator is added part of issue #3

**Comment by Emay-Pandarakutty** [comment]
Approved

**Comment by tohearen** [comment]
Random shark sightings can now be retrieved by the following attributes
- from date time
- to date time
- gps location
- mile radius
- shark population size

The time range, population size and mile radius all impact the number of shark sightings returned. Also, all sightings reported are on gps coordinates that are confirmed to be water.
